### PR TITLE
Multiple Decimal Point Fix

### LINKED ISSUE #9: Multiple decimal points allowed
**Desktop (please complete the following information):**
 - OS: Windows 7
 - elcalc version: 5.0.0-rc.2

**Describe the bug**
It looks like you can add multiple decimal points to a number using both keyboard and GUI buttons.

**To Reproduce**
For example try inputing "1.2.3"

**Expected behavior**
It should not let you enter the second decimal point

### PR DESCRIPTION
**Pull request by MikeM711**
Hi, this is my first actual pull request for an issue, please let me know what you think
Fixes #9

**Fixes for both Keyboard & GUI Buttons:**
- This fixes the issue of being able to input "1.2.3" or any decimal multiple after using an operator/clear/fresh install
- You can start with a decimal point after clear
- You cannot start with a decimal after Enter

### CODE REVIEW

**Comment by xxczaki** [comment]
Thank you :smile:

**Comment by xxczaki** [comment]
btw congrats on making your first PR :zap:

**Comment by MikeM711** [comment]
Thank you! 😊

**Comment by MikeM711** [comment]
Just noticed! My line #105 & #112 should be taken out as they are not useful, I will fix it and make another pull request later today

**Comment by MikeM711** [comment]
Made the fix with #11 
I hope what I am doing is proper GitHub etiquette!

**Pull request merged**
